# Generated by Django 5.0.6 on 2024-07-13 17:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, default='', max_length=255, verbose_name='Описание товара')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Виден ли товар в каталоге')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('text', models.TextField(blank=True, default='', verbose_name='Review text')),
                ('rating', models.PositiveSmallIntegerField(default=1, verbose_name='Cutomer Rating')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Reviews', to='customers.customer', verbose_name='Reviewer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Reviews', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product review',
                'verbose_name_plural': 'Product reviews',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
