# Generated by Django 5.0.6 on 2024-07-04 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_token'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('text', models.TextField(blank=True, default='', verbose_name='Review text')),
                ('rating', models.PositiveSmallIntegerField(default=1, verbose_name='Cutomer Rating')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Reviews', to='customers.customer', verbose_name='Reviewer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Reviews', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product review',
                'verbose_name_plural': 'Product reviews',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
