# Generated by Django 5.0.6 on 2024-07-04 09:34

import uuid

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(default=uuid.UUID('51323ea7-24d9-48a0-a182-89e5e1006aa5'), max_length=255, unique=True, verbose_name='Тикер для пользователя'),
        ),
    ]
